const chapter = [
    {
      "message": "\"Kareler\",(isim değişecek) auto-control bir puzzle oyunudur. \n\nOyunda içi üçgen olan arabaların yuvarlak paraları toplamasını sağlayacaksın. \n\nilk bölüm için hiçbir şey yapmana gerek yok.\n\nbölümü başlatmak ve durdurmak için herhangi bir tuşa bas.",
      "level": {
        "things": [
          [
            "Car",
            "sq_1_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_1",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          3,
          6
        ],
        "editables": [
          "sq_0_2",
          "sq_1_2",
          "sq_2_2",
          "sq_3_2",
          "sq_4_2",
          "sq_4_0",
          "sq_5_0",
          "sq_5_2",
          "sq_0_1",
          "sq_1_1",
          "sq_2_1",
          "sq_3_1",
          "sq_3_0",
          "sq_2_0",
          "sq_1_0",
          "sq_0_0",
          "sq_5_1"
        ]
      }
    },
    {
      "message": "Arabayı istediğin yere koymak için sürükle ve bırak.\n\nBir araba duvara çarptığı zaman arkasına dönüp ters yönde harekete devam edecektir.\n",
      "level": {
        "things": [
          [
            "Car",
            "sq_2_2",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_1",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          3,
          6
        ],
        "editables": [
          "sq_0_2",
          "sq_0_1",
          "sq_1_2",
          "sq_1_1",
          "sq_2_2",
          "sq_2_1",
          "sq_2_0",
          "sq_1_0",
          "sq_0_0",
          "sq_3_0",
          "sq_3_2",
          "sq_3_1",
          "sq_5_2",
          "sq_4_2",
          "sq_4_0",
          "sq_5_0",
          "sq_5_1"
        ]
      }
    },
    {
      "message": "Araba bir tabela ile karşılaştığı zaman yön değiştirir.\n\nArabayı yönlendir.\n",
      "level": {
        "things": [
          [
            "Car",
            "sq_1_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_0_0",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_1_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_3_3",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          5,
          5
        ],
        "editables": [
          "sq_0_4",
          "sq_1_4",
          "sq_2_4",
          "sq_2_3",
          "sq_3_4",
          "sq_4_4",
          "sq_4_3",
          "sq_4_2",
          "sq_4_1",
          "sq_4_0",
          "sq_3_0",
          "sq_3_1",
          "sq_3_2",
          "sq_2_1",
          "sq_2_2",
          "sq_1_2",
          "sq_0_3",
          "sq_0_2",
          "sq_0_1",
          "sq_1_0",
          "sq_1_1",
          "sq_0_0",
          "sq_2_0"
        ]
      }
    },
    {
      "message": "Bir nesne sadece yeşil karelerdeyse onu oynatabilirsin. Onu koyacağın yeni karenin de aynı şekilde yeşil olması lazım. Yeşilde durmayan nesneler sabittir.\n",
      "level": {
        "things": [
          [
            "Car",
            "sq_2_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_4_5",
            [
              1,
              0
            ],
            "green"
          ],
          [
            "Sign",
            "sq_5_4",
            [
              0,
              -1
            ],
            "green"
          ],
          [
            "Sign",
            "sq_4_4",
            [
              -1,
              0
            ],
            "green"
          ],
          [
            "Sign",
            "sq_5_5",
            [
              0,
              1
            ],
            "green"
          ],
          [
            "Coin",
            "sq_4_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_1_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_1_1",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          6,
          6
        ],
        "editables": [
          "sq_0_5",
          "sq_1_5",
          "sq_2_5",
          "sq_5_5",
          "sq_5_4",
          "sq_3_4",
          "sq_4_4",
          "sq_4_5",
          "sq_3_5",
          "sq_2_4",
          "sq_0_4",
          "sq_1_4"
        ]
      }
    },
    {
      "message": "",
      "level": {
        "things": [
          [
            "Car",
            "sq_2_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_5_4",
            [
              0,
              1
            ],
            "green"
          ],
          [
            "Sign",
            "sq_5_5",
            [
              1,
              0
            ],
            "green"
          ],
          [
            "Sign",
            "sq_4_5",
            [
              0,
              -1
            ],
            "green"
          ],
          [
            "Coin",
            "sq_5_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_1_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_3",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          6,
          6
        ],
        "editables": [
          "sq_0_2",
          "sq_0_1",
          "sq_1_1",
          "sq_0_0",
          "sq_1_0",
          "sq_2_0",
          "sq_3_0",
          "sq_4_0",
          "sq_5_0",
          "sq_5_4",
          "sq_5_5",
          "sq_0_5",
          "sq_1_5",
          "sq_2_5",
          "sq_4_5",
          "sq_3_5",
          "sq_4_4",
          "sq_5_3",
          "sq_5_1",
          "sq_0_4"
        ]
      }
    },
    {
      "message": "",
      "level": {
        "things": [
          [
            "Car",
            "sq_7_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_3",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_1",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_7_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_5_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_5_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_2_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_2_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_2_0",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          5,
          8
        ],
        "editables": [
          "sq_6_4",
          "sq_7_4",
          "sq_6_3",
          "sq_7_3",
          "sq_7_1",
          "sq_6_2",
          "sq_6_1",
          "sq_7_2",
          "sq_7_0",
          "sq_6_0",
          "sq_4_4",
          "sq_3_4",
          "sq_4_3",
          "sq_3_3",
          "sq_4_2",
          "sq_3_2",
          "sq_4_1",
          "sq_3_1",
          "sq_4_0",
          "sq_3_0",
          "sq_1_4",
          "sq_0_4",
          "sq_1_3",
          "sq_0_3",
          "sq_1_2",
          "sq_0_2",
          "sq_1_1",
          "sq_0_1",
          "sq_1_0",
          "sq_0_0"
        ]
      }
    },
    {
      "message": "",
      "level": {
        "things": [
          [
            "Car",
            "sq_1_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_1",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_0_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_4_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_0_3",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          5,
          5
        ],
        "editables": [
          "sq_1_4",
          "sq_0_4",
          "sq_1_2",
          "sq_0_2",
          "sq_0_1",
          "sq_1_0",
          "sq_0_0",
          "sq_1_1",
          "sq_1_3"
        ]
      }
    },
    {
      "message": "Her araba, kendi rengindeki parayı toplamalı.",
      "level": {
        "things": [
          [
            "Car",
            "sq_3_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_2_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Sign",
            "sq_0_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_0_1",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_5_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_6_3",
            [
              1,
              0
            ],
            "blue"
          ]
        ],
        "size": [
          6,
          10
        ],
        "editables": [
          "sq_1_5",
          "sq_1_4",
          "sq_0_5",
          "sq_1_3",
          "sq_0_3",
          "sq_0_4",
          "sq_9_2",
          "sq_9_1",
          "sq_8_0",
          "sq_8_2",
          "sq_8_1",
          "sq_9_0",
          "sq_1_2",
          "sq_0_2",
          "sq_1_1",
          "sq_0_1",
          "sq_0_0",
          "sq_1_0",
          "sq_8_5",
          "sq_8_3",
          "sq_9_3",
          "sq_9_4",
          "sq_9_5",
          "sq_8_4"
        ]
      }
    },
    {
      "message": "İçi çember olan nesneler kutudur. Arabalar kutuları ittirebilir. Kutuların renklerine göre ağırlıkları vardır. \n\nTuruncu maviden güçlüdür. Turuncu araba bütün kutuları ittirebilir. Mavi araba sadece mavi kutuları ittirebilir.",
      "level": {
        "things": [
          [
            "Box",
            "sq_2_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_5_3",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_3_3",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Box",
            "sq_7_1",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Sign",
            "sq_6_2",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_3_1",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_6_0",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_3_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_9_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_9_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_9_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_2_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_1_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_0_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_1_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_2_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_2_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_1_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_0_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_0_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_1_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Coin",
            "sq_8_1",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          4,
          10
        ],
        "editables": [
          "sq_6_0",
          "sq_5_0",
          "sq_5_1",
          "sq_6_1",
          "sq_5_3",
          "sq_6_3",
          "sq_6_2",
          "sq_5_2",
          "sq_4_2",
          "sq_3_2",
          "sq_3_3",
          "sq_4_3",
          "sq_3_1",
          "sq_3_0",
          "sq_4_0",
          "sq_4_1"
        ]
      }
    },
    {
      "message": "Turuncu maviden güçlüdür. Eğer iki araba çarpışırsa güçlü olan, ötekini iter ve ters dönmeye zorlar.",
      "level": {
        "things": [
          [
            "Wall",
            "sq_5_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_4_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Box",
            "sq_4_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_1_4",
            [
              -1,
              0
            ],
            "blue"
          ],
          [
            "Car",
            "sq_0_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_5_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_6_3",
            [
              1,
              0
            ],
            "blue"
          ]
        ],
        "size": [
          7,
          8
        ],
        "editables": [
          "sq_3_6",
          "sq_3_5",
          "sq_3_4",
          "sq_3_3",
          "sq_3_2",
          "sq_3_0",
          "sq_2_0",
          "sq_3_1",
          "sq_2_1",
          "sq_2_5",
          "sq_2_6",
          "sq_1_6",
          "sq_0_6",
          "sq_1_5",
          "sq_0_5",
          "sq_1_4",
          "sq_0_4",
          "sq_2_4",
          "sq_2_3",
          "sq_1_3",
          "sq_0_3",
          "sq_0_2",
          "sq_2_2",
          "sq_1_2",
          "sq_1_1",
          "sq_0_1",
          "sq_1_0",
          "sq_0_0"
        ]
      }
    },
    {
      "message": "Bu bölümde turuncu araba sabit.",
      "level": {
        "things": [
          [
            "Wall",
            "sq_5_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Box",
            "sq_4_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Box",
            "sq_4_4",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Car",
            "sq_3_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_2_6",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_2_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_0_5",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_1_5",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Car",
            "sq_1_3",
            [
              0,
              -1
            ],
            "blue"
          ],
          [
            "Sign",
            "sq_3_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_6_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Coin",
            "sq_7_4",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          7,
          8
        ],
        "editables": [
          "sq_4_6",
          "sq_3_6",
          "sq_3_5",
          "sq_2_6",
          "sq_2_5",
          "sq_1_6",
          "sq_1_5",
          "sq_0_5",
          "sq_2_4",
          "sq_3_4",
          "sq_3_3",
          "sq_2_3",
          "sq_1_3",
          "sq_0_4",
          "sq_0_3",
          "sq_1_4",
          "sq_0_6",
          "sq_4_3",
          "sq_1_2",
          "sq_0_2",
          "sq_0_1",
          "sq_4_1",
          "sq_4_0",
          "sq_0_0",
          "sq_1_1",
          "sq_1_0",
          "sq_2_1",
          "sq_2_0",
          "sq_3_1",
          "sq_3_0",
          "sq_4_5",
          "sq_2_2"
        ]
      }
    },
    {
      "message": "İki sapı olan oklar pistondur. Pistonlar önlerine gelen her şeyi iterler. Arabaların yönünü değiştirirler.",
      "level": {
        "things": [
          [
            "Piston",
            "sq_1_0",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_0_1",
            [
              -1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_4_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_1_1",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_5_1",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Sign",
            "sq_6_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_3_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_5_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_3_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_3_3",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          7,
          7
        ],
        "editables": [
          "sq_0_6",
          "sq_1_6",
          "sq_2_6",
          "sq_1_5",
          "sq_0_5",
          "sq_0_4",
          "sq_4_6",
          "sq_5_5",
          "sq_6_4",
          "sq_6_6",
          "sq_5_6",
          "sq_6_5",
          "sq_6_2",
          "sq_6_1",
          "sq_5_1",
          "sq_4_0",
          "sq_6_0",
          "sq_5_0",
          "sq_0_1",
          "sq_0_2",
          "sq_1_1",
          "sq_2_0",
          "sq_1_0",
          "sq_0_0"
        ]
      }
    },
    {
      "message": "",
      "level": {
        "things": [
          [
            "Car",
            "sq_2_8",
            [
              0,
              -1
            ],
            "blue"
          ],
          [
            "Piston",
            "sq_0_8",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_1_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_1_7",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_0_6",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_1_5",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_1_8",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_2_6",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_2_7",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_0_7",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_7_1",
            [
              1,
              0
            ],
            "blue"
          ]
        ],
        "size": [
          9,
          9
        ],
        "editables": [
          "sq_0_6",
          "sq_1_6",
          "sq_2_6",
          "sq_2_7",
          "sq_1_7",
          "sq_0_7",
          "sq_0_8",
          "sq_1_8",
          "sq_2_8",
          "sq_1_5",
          "sq_2_4",
          "sq_3_3",
          "sq_4_2",
          "sq_5_1",
          "sq_3_6",
          "sq_4_5",
          "sq_5_4",
          "sq_6_3"
        ]
      }
    },
    {
      "message": "Bir kapı, sadece kendi renginde olan bir araba veya kutunun kendinden geçmesine izin verir.\n",
      "level": {
        "things": [
          [
            "Car",
            "sq_3_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_8_2",
            [
              -1,
              0
            ],
            "blue"
          ],
          [
            "Coin",
            "sq_4_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Coin",
            "sq_0_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Gate",
            "sq_5_2",
            [
              1,
              0
            ],
            "blue"
          ]
        ],
        "size": [
          5,
          9
        ],
        "editables": []
      }
    },
    {
      "message": "Bir kapıya bir kutu ittirilirse, kapı o kutunun rengini alır. Kutu kaybolur.",
      "level": {
        "things": [
          [
            "Car",
            "sq_0_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Box",
            "sq_1_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_2_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Box",
            "sq_3_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Wall",
            "sq_5_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_4",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_3",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_5_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_6_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_7_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_8_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_7_2",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Coin",
            "sq_8_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Gate",
            "sq_5_2",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          5,
          9
        ],
        "editables": [
          "sq_3_4",
          "sq_3_3",
          "sq_3_2",
          "sq_2_0",
          "sq_4_0",
          "sq_3_0",
          "sq_3_1",
          "sq_4_2",
          "sq_4_3",
          "sq_4_4",
          "sq_2_4",
          "sq_0_4",
          "sq_0_3",
          "sq_1_4",
          "sq_2_3",
          "sq_1_3",
          "sq_2_2",
          "sq_1_2",
          "sq_2_1",
          "sq_1_1",
          "sq_0_2",
          "sq_0_1",
          "sq_1_0",
          "sq_0_0",
          "sq_4_1"
        ]
      }
    },
    {
      "message": "",
      "level": {
        "things": [
          [
            "Wall",
            "sq_1_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_0_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_1_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_0_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_2_1",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Wall",
            "sq_2_0",
            [
              1,
              0
            ],
            "orange"
          ],
          [
            "Car",
            "sq_2_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Piston",
            "sq_6_0",
            [
              0,
              1
            ],
            "orange"
          ],
          [
            "Piston",
            "sq_8_0",
            [
              0,
              -1
            ],
            "orange"
          ],
          [
            "Box",
            "sq_7_0",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Coin",
            "sq_0_2",
            [
              1,
              0
            ],
            "blue"
          ],
          [
            "Gate",
            "sq_1_2",
            [
              1,
              0
            ],
            "orange"
          ]
        ],
        "size": [
          3,
          9
        ],
        "editables": [
          "sq_4_2",
          "sq_5_2",
          "sq_6_2",
          "sq_8_1",
          "sq_7_1",
          "sq_7_2",
          "sq_8_2",
          "sq_8_0",
          "sq_7_0",
          "sq_5_0",
          "sq_4_0",
          "sq_4_1",
          "sq_5_1",
          "sq_6_0",
          "sq_6_1"
        ]
      }
    }
  ]